### PR TITLE
ReadMe

### PR DESCRIPTION
**Pull request by Khalid4447**
ReadMe added

Issue #8

### CODE REVIEW

**Comment by abdulraoof1997** [comment]
No description found, please add description

**Comment by moode061** [comment]
Also, please assign someone to review your code!

**Comment by abdulraoof1997** [comment]
Agreed. This is bad practice

**Review by abdulraoof1997 — COMMENTED** [review]
No description found

**Review by moode061 — COMMENTED** [review]
need more description

**Pull request merged**
